### ISSUE TITLE
No Export

### ISSUE THREAD

**Issue by SchnellerReifen** [840922704/BLE_DMM_Client#7] opened 2023-08-25 19:27 UTC
Hello here and thank you for the tool.

Im using it for windows 10 but there is no export possible

![grafik](https://github.com/840922704/BLE_DMM_Client/assets/7966676/9e415923-52e8-411c-9454-8adea983a6d2)

everything i can klick there doesnt work with export
is it a bug?

**Comment by 840922704** [comment] 2023-08-26 05:05
Thanks for your reporting.
It's a bug, but it will not be fixed in the future. Plz set the export path and click the check box at the bottom of the windows instead.
There are two reasons not fixing this export way yet: 1) No gear information about the multimeter. 2)  Limited buffer space in memory. Data will lost when buffer restriction reached or out of memory.
All in all, plz use the check box instead. That will export data directly to your disk.

**Comment by 840922704** [comment] 2023-08-26 09:10
I did further research. It's caused by nuitka's incomplete support for pyqt5. There maybe some errors occur when nuitka transforming python code to c code.
Just install all packaged in a virtual env and run "python main.py" and it will work normally.
Still recommend using the check box method instead.

**Comment by 840922704** [comment] 2023-08-27 10:28
I just upgraded the backend from pyqt5 to pyside6. It seems that the export still broken after packed by nuitka. Anyway finally added multi-devices support and fixed some variable issues. I will update later.

**Comment by 840922704** [comment] 2023-08-29 14:50
V3.2 released. Please try the new one. Nuitka will occur crash with pyqtgraph (see issue #1532 in nuitka, Github). So the export function in pyqtgraph had been deleted.

**Comment by 840922704** [comment] 2023-09-04 03:19
I add back the export item in V3.2.1. Using pyinstaller not nuitka beacuse of seriously memory leak problem.

**Closed as completed by 840922704** 2023-09-04 03:19 UTC
